Fix exceptions related to snappy compression:
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.common.record.CompressionType$SnappyConstructors
        at org.apache.kafka.common.record.CompressionType$3.wrapForOutput(CompressionType.java:81) ~[org.apache.servicemix.bundles.kafka-clients-2.4.0_1.jar:?]
        ... 30 more