NMS-12788: fully enable NTLMv2; get SMBv2 by move to jcifs-ng and j-interop-ng (#3134)
* NMS-12788: fully enable NTLMv2; get SMBv2 by move to jcifs-ng and j-interop-ng

* well they changed the API anyway so let's go all the way to latest
jcifs-ng; fix tests

* oops a space

* Update protocols/cifs/src/main/java/org/opennms/netmgt/poller/monitors/JCifsMonitor.java

Co-authored-by: Jesse White <jwhite08@gmail.com>

* use SingletonContext if config of timeout fails

* maybe it should compile

* bump bcprov to latest

* bc security provider preventing karaf shell from starting

* call the correct method for the cast to work

* no need to wrap this one

* getting NoClassDefFoundError for two classes in two of these packages, and they were not added to the Import-Package list by the wrap feature so hoping this resolves it.

* use the correct group / artifact for j-interop 3

Co-authored-by: Jesse White <jwhite08@gmail.com>